parameters:
    pim_extended_attribute_type.datagrid.extension.formatter.property.product_value.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\DataGrid\Extension\Formatter\Property\ProductValue\DateCollectionProperty

services:
    pim_extended_attribute_type.datagrid.extension.formatter.property.product_value.date_collection:
        class: '%pim_extended_attribute_type.datagrid.extension.formatter.property.product_value.date_collection.class%'
        arguments:
            - '@twig'
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: product_value_date_collection }
