parameters:
    pim_extended_attribute_type.array_converter.flat_to_standard.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\ArrayConverter\FlatToStandard\Product\ValueConverter\DateCollectionConverter
    pim_extended_attribute_type.array_converter.standard_to_flat.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\ArrayConverter\StandardToFlat\Product\ValueConverter\DateCollectionConverter

services:
    pim_extended_attribute_type.array_converter.standard_to_flat.product.value_converter.date_collection:
        class: '%pim_extended_attribute_type.array_converter.standard_to_flat.date_collection.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - ['pim_catalog_date_collection']
        tags:
            - { name: 'pim_connector.array_converter.standard_to_flat.product.value_converter' }

    pim_extended_attribute_type.array_converter.flat_to_standard.product.value_converter.date_collection:
        class: '%pim_extended_attribute_type.array_converter.flat_to_standard.date_collection.class%'
        arguments:
            - ['pim_catalog_date_collection']
        tags:
            - { name: 'pim_connector.array_converter.flat_to_standard.product.value_converter' }
