parameters:
    pim_extended_attribute_type.completeness.checker.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\Completeness\Checker\DateCollectionCompleteChecker

services:
    pim_extended_attribute_type.completeness.checker.date_collection:
        class: '%pim_extended_attribute_type.completeness.checker.date_collection.class%'
        tags:
            - { name: pim_catalog.completeness.checker.product_value, priority: 100 }
