parameters:
    pim_catalog.comparator.attribute.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\Updater\Comparator\DateCollectionComparator

services:
    pim_extended_attribute_type.comparator.attribute.date_collection:
        class: '%pim_catalog.comparator.attribute.date_collection.class%'
        arguments:
            - ['pim_catalog_date_collection']
        tags:
            - { name: pim_catalog.attribute.comparator }
