parameters:
    pim_extended_attribute_type.denormalizer.flat.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\Normalizer\Flat\DateCollectionDenormalizerFlat

services:
    pim_extended_attribute_type.denormalizer.standard.date_collection:
        class: '%pim_catalog.denormalizer.standard.base_value.class%'
        arguments:
            - ['pim_catalog_date_collection']
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }

    pim_extended_attribute_type.denormalizer.flat.date_collection:
        class: '%pim_extended_attribute_type.denormalizer.flat.date_collection.class%'
        arguments:
            - ['pim_catalog_date_collection']
        tags:
            - { name: pimee_versioning.serializer.normalizer, priority: 90 }
