parameters:
    pim_extended_attribute_type.provider.field.date_collection.class: Pim\Bundle\DateCollectionTypeBundle\Provider\Field\DateCollectionProvider

services:
    pim_extended_attribute_type.provider.field.date_collection:
        class: '%pim_extended_attribute_type.provider.field.date_collection.class%'
        tags:
            - { name: pim_enrich.provider.field, priority: 100 }
