services:
    pim_elastic_search.query.filter.date_collection:
        class: %pim_elastic_search.query.filter.string.class%
        arguments:
            - @pim_catalog.validator.helper.attribute
            - ['pim_catalog_date_collection']
            - ['CONTAINS', 'DOES NOT CONTAIN', 'EMPTY', 'NOT EMPTY']
        tags:
            - { name: 'pim_elastic_search.query.filter', priority: 30 }
